name: coverity-scan

on:
  schedule:
    - cron:  '0 6 * * *' # Daily at 6:00 UTC

jobs:
  Coverity:
    if: github.repository == 'CESNET/UltraGrid' || github.repository == 'MartinPulec/UltraGrid'
    runs-on: ubuntu-latest
    env:
      sdk_pass: ${{ secrets.sdk_pass }}
      coverity_token: ${{ secrets.coverity_token }}

    steps:
    - name: Download Coverity build tool
      run: |
        cd /tmp
        wget --no-verbose https://scan.coverity.com/download/linux64 --post-data "token=$coverity_token&project=UltraGrid" -O coverity_tool.tgz
        tar xaf coverity_tool.tgz
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: bootstrap
      run: .github/scripts/Linux/prepare.sh
    - name: Cache static Qt
      id: cache-qt-linux
      uses: actions/cache@v1
      with:
        path: /usr/local/qt
        key: cache-qt-linux
    - name: Build static Qt
      if: steps.cache-qt-linux.outputs.cache-hit != 'true'
      run: .github/scripts/Linux/build-qt.sh
    - name: configure
      run: ./autogen.sh --enable-qt --enable-static-qt --with-cuda-host-compiler=gcc-6 --enable-plugins
    - name: Build with cov-build
      run: |
        /tmp/cov-analysis*/bin/cov-build --dir cov-int make -j 2
    - name: Submit the result to Coverity Scan
      run: |
        tar caf ultragrid.tar.xz cov-int
        curl --form token=$coverity_token \
          --form email=pulec@cesnet.cz \
          --form file=@ultragrid.tar.xz \
          --form version="date +%F" \
          --form description="master build" \
          https://scan.coverity.com/builds?project=UltraGrid

# vi: set expandtab sw=2:
